name: Install TeX Live
description: Install a minimal TeX Live version and a customizable list of packages
author: Marcel Krüger

branding:
  icon: download
  color: blue

inputs:
  repository:
    description: 'The repository to install TeX Live from'
    required: false
  package_file:
    description: 'A file listing the packages to install'
    required: false
  packages:
    description: 'Which packages to install'
    required: false
  cache_version:
    description: 'A version number to allow forcing cache invalidation'
    default: 0
  accept-stale:
    description: 'Do not fail if unable to update but an outdated version is available'
    required: false
    default: true

outputs:
  cache_key:
    description: "The updated or generated cache"
    value: ${{ steps.key.outputs.key }}

runs:
  using: node20
  main: dist/index.js
