name: Lint Codebase

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Lint Codebase
        run: "npm run format:write && npm run lint"
